server:
  port: 8888

spring:
  application:
    name: Gateway
  cloud:
    consul:
      host: consul-container
      port: 8500
      discovery:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
